# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: List all tasks
    cmds:
      - task --list-all

  build:
    desc: build OpenBinary.exe
    sources:
      - ./*.go
    generates:
      - ./bin/OpenBinary.exe
    cmds:
      - go build -o bin/OpenBinary.exe .
      - task: publish

  publish:
    cmds:
      - cp bin/OpenBinary.exe /c/Tools
